# Generated by Django 4.0.4 on 2022-04-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newmodel',
            options={'verbose_name': 'Hír', 'verbose_name_plural': 'Hírek'},
        ),
    ]
